language: ruby
branches:
  only:
    - master
install:
  - npm install -g grunt-cli
  - gem install --no-document jekyll
  - npm install -g bower
  - npm install
  - bower install
  - gem install scss-lint
script: grunt build
