language: ruby
branches:
  only:
    - master
install:
  - npm install -g grunt-cli
  - gem install --no-document jekyll
  - npm install -g bower
  - npm install
  - bower install
script: grunt build
